-- Personal Spending Dashboard — PostgreSQL schema contract.
--
-- This is the fixed relational contract for the JPA deliverable. Map your
-- entities onto these tables, columns, keys, and nullability exactly.
-- Hibernate runs with ddl-auto: validate, so the schema must already exist
-- before the application or the repository tests start.
--
-- Identity columns are GENERATED BY DEFAULT so that the seed can insert
-- explicit keys and the application can still let the database assign them.

BEGIN;

DROP TABLE IF EXISTS spending_insights CASCADE;
DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS merchants CASCADE;
DROP TABLE IF EXISTS accounts CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL,
    display_name  VARCHAR(120) NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE TABLE accounts (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT       NOT NULL,
    name          VARCHAR(120) NOT NULL,
    account_type  VARCHAR(20)  NOT NULL,
    opened_on     DATE         NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_accounts_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_accounts_type CHECK (account_type IN ('CHECKING', 'SAVINGS', 'CREDIT_CARD')),
    CONSTRAINT uq_accounts_user_name UNIQUE (user_id, name)
);

CREATE TABLE merchants (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(160) NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_merchants_name UNIQUE (name)
);

-- parent_category_id models the category hierarchy. The JPA deliverable does
-- not map it — the column stays in the contract because the dashboard read
-- must not depend on a redesigned schema.
CREATE TABLE categories (
    id                  BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(120) NOT NULL,
    parent_category_id  BIGINT,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_categories_parent FOREIGN KEY (parent_category_id) REFERENCES categories (id),
    CONSTRAINT uq_categories_name UNIQUE (name)
);

CREATE TABLE transactions (
    id            BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id    BIGINT         NOT NULL,
    merchant_id   BIGINT         NOT NULL,
    category_id   BIGINT         NOT NULL,
    amount        NUMERIC(12, 2) NOT NULL,
    direction     VARCHAR(10)    NOT NULL,
    occurred_on   DATE           NOT NULL,
    description   VARCHAR(255)   NOT NULL,
    created_at    TIMESTAMPTZ    NOT NULL DEFAULT now(),
    CONSTRAINT fk_transactions_account  FOREIGN KEY (account_id)  REFERENCES accounts (id),
    CONSTRAINT fk_transactions_merchant FOREIGN KEY (merchant_id) REFERENCES merchants (id),
    CONSTRAINT fk_transactions_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT ck_transactions_amount CHECK (amount > 0),
    CONSTRAINT ck_transactions_direction CHECK (direction IN ('DEBIT', 'CREDIT'))
);

-- Supports the user-scoped, half-open month read.
CREATE INDEX ix_transactions_account_occurred_on
    ON transactions (account_id, occurred_on DESC, id DESC);

-- Spending insights are part of the relational contract but out of scope for
-- the JPA mapping work.
CREATE TABLE spending_insights (
    id             BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT      NOT NULL,
    period_start   DATE        NOT NULL,
    period_end     DATE        NOT NULL,
    summary        TEXT        NOT NULL,
    generated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_spending_insights_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_spending_insights_period CHECK (period_end > period_start)
);

COMMIT;
